# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170818_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='image_products', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=32, verbose_name='название'),
        ),
    ]
