# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20170818_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Gem',
        ),
    ]
