# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_products'),
        ),
    ]
